// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopServiceClient interface {
	GetStoreById(ctx context.Context, in *GetStoreByIdReq, opts ...grpc.CallOption) (*StoreDto, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

var shopServiceGetStoreByIdStreamDesc = &grpc.StreamDesc{
	StreamName: "GetStoreById",
}

func (c *shopServiceClient) GetStoreById(ctx context.Context, in *GetStoreByIdReq, opts ...grpc.CallOption) (*StoreDto, error) {
	out := new(StoreDto)
	err := c.cc.Invoke(ctx, "/ShopService/GetStoreById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceService is the service API for ShopService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterShopServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type ShopServiceService struct {
	GetStoreById func(context.Context, *GetStoreByIdReq) (*StoreDto, error)
}

func (s *ShopServiceService) getStoreById(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetStoreById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/ShopService/GetStoreById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetStoreById(ctx, req.(*GetStoreByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterShopServiceService registers a service implementation with a gRPC server.
func RegisterShopServiceService(s grpc.ServiceRegistrar, srv *ShopServiceService) {
	srvCopy := *srv
	if srvCopy.GetStoreById == nil {
		srvCopy.GetStoreById = func(context.Context, *GetStoreByIdReq) (*StoreDto, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GetStoreById not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "ShopService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetStoreById",
				Handler:    srvCopy.getStoreById,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "store.proto",
	}

	s.RegisterService(&sd, nil)
}
